name: Deploy Frontend App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/

      - name: Set permissions
        run: |
          sudo chown -R www-data:www-data /var/www/html/

      - name: Reload Nginx
        run: sudo systemctl reload nginx